USE [MuOnline]
GO

-- =============================================
-- Populate Bot Class Configurations (7 Classes × 7 Configs Each)
-- Note: Inventory and MagicList hex values should be customized based on your server's item codes
-- =============================================

DELETE FROM [dbo].[BotClassConfigs]
GO

-- =============================================
-- DARK WIZARD (Class 0) - 7 Configurations
-- =============================================

-- Config 0: Starter DW (Energy focused)
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(0, 0, 'DW Starter', 2000, 2000, 2000, 5000, 0, 9, 12, 16, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF020009FF0CFF10FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 1: Balanced DW
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(0, 1, 'DW Balanced', 2500, 2500, 2500, 5500, 0, 9, 12, 16, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF020009FF0CFF10FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 2: High Energy DW
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(0, 2, 'DW High Energy', 2000, 2000, 2500, 6000, 0, 9, 12, 16, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF020009FF0CFF10FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 3: Tank DW
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(0, 3, 'DW Tank', 2500, 2000, 4000, 4500, 0, 9, 12, 16, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF020009FF0CFF10FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 4: Speed DW
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(0, 4, 'DW Speed', 2000, 3500, 2000, 5000, 0, 9, 12, 16, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF020009FF0CFF10FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 5: Elite DW
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(0, 5, 'DW Elite', 3000, 3000, 3500, 6500, 0, 9, 12, 16, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF020009FF0CFF10FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 6: Ultimate DW
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(0, 6, 'DW Ultimate', 4000, 4000, 4000, 8000, 0, 9, 12, 16, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF020009FF0CFF10FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- =============================================
-- DARK KNIGHT (Class 16) - 7 Configurations
-- =============================================

-- Config 0: Starter DK
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(16, 0, 'DK Starter', 5000, 4500, 5500, 4000, 0, 44, 41, 48, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF022CFF29FF30FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 1: Balanced DK
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(16, 1, 'DK Balanced', 6000, 5000, 6000, 4500, 0, 44, 41, 48, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF022CFF29FF30FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 2: Strength DK
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(16, 2, 'DK Strength', 7000, 4500, 5500, 4000, 0, 44, 41, 48, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF022CFF29FF30FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 3: Tank DK
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(16, 3, 'DK Tank', 5500, 4000, 7500, 4000, 0, 44, 41, 48, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF022CFF29FF30FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 4: Speed DK
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(16, 4, 'DK Speed', 5500, 6500, 5000, 4000, 0, 44, 41, 48, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF022CFF29FF30FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 5: Elite DK
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(16, 5, 'DK Elite', 7500, 6500, 7000, 5500, 0, 44, 41, 48, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF022CFF29FF30FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 6: Ultimate DK
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(16, 6, 'DK Ultimate', 9000, 8000, 9000, 7000, 0, 44, 41, 48, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF022CFF29FF30FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- =============================================
-- ELF (Class 32) - 7 Configurations
-- =============================================

-- Config 0: Starter ELF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(32, 0, 'ELF Starter', 2500, 4500, 2500, 3000, 0, 24, 52, 26, 27, 28,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0218FF34FF1AFF1BFF1CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 1: Balanced ELF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(32, 1, 'ELF Balanced', 3000, 5000, 3000, 3500, 0, 24, 52, 26, 27, 28,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0218FF34FF1AFF1BFF1CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 2: Dexterity ELF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(32, 2, 'ELF Dexterity', 2500, 6000, 2500, 3000, 0, 24, 52, 26, 27, 28,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0218FF34FF1AFF1BFF1CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 3: Tank ELF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(32, 3, 'ELF Tank', 3000, 4500, 4500, 3000, 0, 24, 52, 26, 27, 28,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0218FF34FF1AFF1BFF1CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 4: Energy ELF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(32, 4, 'ELF Energy', 2500, 4500, 2500, 4500, 0, 24, 52, 26, 27, 28,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0218FF34FF1AFF1BFF1CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 5: Elite ELF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(32, 5, 'ELF Elite', 4000, 6500, 4000, 5000, 0, 24, 52, 26, 27, 28,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0218FF34FF1AFF1BFF1CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 6: Ultimate ELF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(32, 6, 'ELF Ultimate', 5500, 8500, 5500, 7000, 0, 24, 52, 26, 27, 28,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0218FF34FF1AFF1BFF1CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- =============================================
-- MAGIC GLADIATOR (Class 48) - 7 Configurations
-- =============================================

-- Config 0: Starter MG
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(48, 0, 'MG Starter', 4000, 3000, 4000, 4000, 0, 8, 55, -1, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0208FF37FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 1: Balanced MG
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(48, 1, 'MG Balanced', 5000, 4000, 5000, 5000, 0, 8, 55, -1, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0208FF37FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 2: Strength MG
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(48, 2, 'MG Strength', 6000, 3500, 4500, 4500, 0, 8, 55, -1, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0208FF37FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 3: Tank MG
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(48, 3, 'MG Tank', 4500, 3000, 6500, 4500, 0, 8, 55, -1, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0208FF37FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 4: Energy MG
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(48, 4, 'MG Energy', 4000, 3000, 4000, 6000, 0, 8, 55, -1, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0208FF37FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 5: Elite MG
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(48, 5, 'MG Elite', 6500, 5000, 6500, 6500, 0, 8, 55, -1, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0208FF37FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 6: Ultimate MG
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(48, 6, 'MG Ultimate', 8500, 7000, 8500, 8500, 0, 8, 55, -1, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0208FF37FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- =============================================
-- DARK LORD (Class 64) - 7 Configurations
-- =============================================

-- Config 0: Starter DL
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(64, 0, 'DL Starter', 4500, 3500, 4500, 2500, 5000, 65, 61, 64, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0241FF3DFF40FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 1: Balanced DL
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(64, 1, 'DL Balanced', 5500, 4500, 5500, 3500, 6000, 65, 61, 64, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0241FF3DFF40FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 2: Strength DL
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(64, 2, 'DL Strength', 6500, 4000, 5000, 3000, 6000, 65, 61, 64, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0241FF3DFF40FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 3: Tank DL
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(64, 3, 'DL Tank', 5000, 3500, 7000, 3000, 6000, 65, 61, 64, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0241FF3DFF40FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 4: Command DL
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(64, 4, 'DL Command', 5000, 4000, 5000, 3000, 7500, 65, 61, 64, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0241FF3DFF40FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 5: Elite DL
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(64, 5, 'DL Elite', 7000, 6000, 7000, 5000, 8500, 65, 61, 64, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0241FF3DFF40FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 6: Ultimate DL
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(64, 6, 'DL Ultimate', 9000, 8000, 9000, 7000, 11000, 65, 61, 64, -1, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF0241FF3DFF40FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- =============================================
-- SUMMONER (Class 80) - 7 Configurations
-- =============================================

-- Config 0: Starter SUM
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(80, 0, 'SUM Starter', 2000, 2000, 2000, 5000, 0, 214, 215, 217, 218, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02D6FFD7FFD9FFDAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 1: Balanced SUM
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(80, 1, 'SUM Balanced', 2500, 2500, 2500, 6000, 0, 214, 215, 217, 218, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02D6FFD7FFD9FFDAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 2: Energy SUM
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(80, 2, 'SUM Energy', 2000, 2000, 2500, 7000, 0, 214, 215, 217, 218, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02D6FFD7FFD9FFDAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 3: Tank SUM
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(80, 3, 'SUM Tank', 2500, 2000, 4500, 5500, 0, 214, 215, 217, 218, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02D6FFD7FFD9FFDAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 4: Curse SUM
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(80, 4, 'SUM Curse', 2500, 2500, 2500, 6500, 0, 214, 215, 217, 218, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02D6FFD7FFD9FFDAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 5: Elite SUM
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(80, 5, 'SUM Elite', 4000, 4000, 4000, 8000, 0, 214, 215, 217, 218, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02D6FFD7FFD9FFDAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 6: Ultimate SUM
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(80, 6, 'SUM Ultimate', 5500, 5500, 5500, 10000, 0, 214, 215, 217, 218, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02D6FFD7FFD9FFDAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- =============================================
-- RAGE FIGHTER (Class 96) - 7 Configurations
-- =============================================

-- Config 0: Starter RF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(96, 0, 'RF Starter', 4500, 4500, 4500, 2000, 0, 264, 263, 266, 268, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02010801070801090801FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 1: Balanced RF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(96, 1, 'RF Balanced', 5500, 5500, 5500, 3000, 0, 264, 263, 266, 268, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02010801070801090801FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 2: Strength RF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(96, 2, 'RF Strength', 7000, 5000, 5000, 2500, 0, 264, 263, 266, 268, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02010801070801090801FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 3: Tank RF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(96, 3, 'RF Tank', 5000, 4500, 7500, 2500, 0, 264, 263, 266, 268, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02010801070801090801FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 4: Dexterity RF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(96, 4, 'RF Dexterity', 5000, 7000, 5000, 2500, 0, 264, 263, 266, 268, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02010801070801090801FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 5: Elite RF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(96, 5, 'RF Elite', 7500, 7500, 7500, 4500, 0, 264, 263, 266, 268, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02010801070801090801FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

-- Config 6: Ultimate RF
INSERT INTO [dbo].[BotClassConfigs] 
(ClassCode, ConfigIndex, ConfigName, Strength, Dexterity, Vitality, Energy, Leadership, MainSkill, SecondarySkill, Buff1, Buff2, Buff3, InventoryHex, MagicListHex, IsEnabled)
VALUES 
(96, 6, 'RF Ultimate', 10000, 10000, 10000, 6000, 0, 264, 263, 266, 268, -1,
'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
'0xFF01FF02010801070801090801FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
1)

GO

PRINT 'Bot class configurations populated successfully'
PRINT CAST((SELECT COUNT(*) FROM BotClassConfigs) AS VARCHAR) + ' configurations inserted (7 classes × 7 configs = 49)'
GO
